"""Generate fork-ready Chuckbot module source from a Saltlick workflow."""

from __future__ import annotations

import json
import re
from typing import Any

from .spec import WorkflowSpec


def python_name(value: str) -> str:
    """Return a valid lowercase package/module name."""
    normalized = re.sub(r"[^a-z0-9]+", "_", value.strip().lower()).strip("_")
    if not normalized or not normalized[0].isalpha():
        normalized = f"bot_{normalized or 'workflow'}"
    return normalized[:64]


def render_jobs_py(spec: WorkflowSpec | dict[str, Any]) -> str:
    """Render a reviewed module handler that uses Saltlick's tested engine."""
    workflow = spec if isinstance(spec, WorkflowSpec) else WorkflowSpec.from_dict(spec)
    recipe_json = json.dumps(workflow.as_dict(), indent=4, sort_keys=True)
    return f'''"""Generated by Saltlick. Edit freely in your fork."""

import json

from chuck_salt_shack.service import execute_workflow
from chuck_salt_shack.spec import recipe_with_invocation


WORKFLOW = json.loads({recipe_json!r})


def run(ctx, payload):
    """Run this workflow inside Chuck the Buckbot Framework."""
    unknown = set(payload) - {{"inputs", "arguments", "confirm_live"}}
    if unknown:
        raise ValueError(
            "unsupported run argument(s): " + ", ".join(sorted(unknown))
        )
    apply_job = ctx.job_name == "apply"
    if apply_job and payload.get("confirm_live") is not True:
        raise ValueError("live run requires confirm_live=true")
    recipe = recipe_with_invocation(
        WORKFLOW,
        inputs=payload.get("inputs"),
        arguments=payload.get("arguments"),
    )
    site = ctx.site(
        recipe["wiki"]["code"],
        recipe["wiki"]["family"],
    )
    dry_run = not apply_job or bool(ctx.config.get("dry_run", False))
    return execute_workflow(site, recipe, dry_run=dry_run, ctx=ctx)
'''


def render_module_toml(spec: WorkflowSpec | dict[str, Any]) -> str:
    """Render a minimal manifest for a generated framework module."""
    workflow = spec if isinstance(spec, WorkflowSpec) else WorkflowSpec.from_dict(spec)
    name = python_name(workflow.name)
    title = workflow.name.replace('"', '\\"')
    return f'''name = "{name}"
title = "{title}"
repo = "https://github.com/your-name/{name}"
entry_point = "modules.{name}.jobs:run"
ui = false
redis_namespace = "{name}"
rights = ["run_jobs", "apply_changes"]

[[worker_jobs]]
name = "preview"
handler = "modules.{name}.jobs:run"
concurrency_policy = "allow"
timeout_seconds = 900
enabled = true

[[worker_jobs]]
name = "apply"
handler = "modules.{name}.jobs:run"
concurrency_policy = "forbid"
required_right = "apply_changes"
timeout_seconds = 1800
enabled = true
'''
